name: Install Dev Tools CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make script executable
      run: chmod +x install-dev-tools.sh

    - name: Run install script
      run: ./install-dev-tools.sh

